# Generated by Django 5.2.12 on 2026-04-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("church", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="church",
            name="members_count",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="description",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="price",
        ),
        migrations.AddField(
            model_name="church",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="church",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_members",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="church",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="church",
            name="hubspot_company_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="church",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="church",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="church",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="church",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="church",
            index=models.Index(fields=["is_active", "country"], name="churches_is_acti_c4e705_idx"),
        ),
        migrations.AlterModelTable(
            name="gateway",
            table="gateways",
        ),
        migrations.AlterModelTable(
            name="plan",
            table="plans",
        ),
    ]
