# Generated by Django 5.2.12 on 2026-04-01 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="article",
            new_name="kb_articles_state_ae9989_idx",
            old_name="kb_articles_state_cat_idx",
        ),
    ]
