# Generated by Django 5.2.12 on 2026-04-01 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_event_t_f5eefa_idx",
            old_name="webhook_events_type_processed_idx",
        ),
    ]
