# Generated by Django 5.2.15 on 2026-08-22 18:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTECTED_TABLES = ("n8n_outbox_events", "hubspot_reconciliation_cursors")
CLIENT_ROLES = ("anon", "authenticated")


def protect_inbound_tables(_apps, schema_editor) -> None:
    """Keep operational delivery data inaccessible to Supabase client roles."""
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        roles = {str(row[0]) for row in cursor.fetchall()}
        for table in PROTECTED_TABLES:
            qualified = f"public.{quote(table)}"
            cursor.execute(
                f"COMMENT ON TABLE {qualified} IS "
                "'JUDAH operational integration data; direct client access is prohibited.'"
            )
            for role in roles:
                cursor.execute(f"REVOKE ALL PRIVILEGES ON TABLE {qualified} FROM {quote(role)}")
            cursor.execute(f"ALTER TABLE {qualified} ENABLE ROW LEVEL SECURITY")


def restore_inbound_table_access(_apps, schema_editor) -> None:
    """Reverse only the access changes introduced by this migration."""
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        roles = {str(row[0]) for row in cursor.fetchall()}
        for table in PROTECTED_TABLES:
            qualified = f"public.{quote(table)}"
            cursor.execute(f"ALTER TABLE {qualified} DISABLE ROW LEVEL SECURITY")
            for role in roles:
                cursor.execute(
                    f"GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER "
                    f"ON TABLE {qualified} TO {quote(role)}"
                )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agents", "0008_remove_legacy_identification_triage"),
        ("webhooks", "0006_drop_legacy_event_id_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[("webhook", "Webhook"), ("reconciliation", "Reconciliation")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="hubspot_contact_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="hubspot_thread_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="hubspot_ticket_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="ignored_reason",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="occurred_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="portal_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="processing_status",
            field=models.CharField(
                choices=[("RECEIVED", "Received"), ("READY", "Ready"), ("IGNORED", "Ignored"), ("ERROR", "Error")],
                db_index=True,
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="source",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="message_id",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="HubSpotReconciliationCursor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hubspot_thread_id", models.CharField(max_length=100, unique=True)),
                ("last_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("last_message_created_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hubspot_reconciliation_cursor",
                        to="ai_agents.conversationinstance",
                    ),
                ),
            ],
            options={
                "db_table": "hubspot_reconciliation_cursors",
                "indexes": [models.Index(fields=["next_attempt_at", "locked_at"], name="idx_hs_reconcile_claim")],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("destination", models.CharField(default="n8n_bot", max_length=50)),
                ("event_type", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("RETRY_SCHEDULED", "Retry scheduled"),
                            ("DELIVERED", "Delivered"),
                            ("DEAD_LETTER", "Dead letter"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                ("available_at", models.DateTimeField(db_index=True)),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("dead_lettered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webhook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_event",
                        to="webhooks.webhookevent",
                    ),
                ),
            ],
            options={
                "db_table": "n8n_outbox_events",
                "ordering": ["available_at", "created_at"],
                "indexes": [
                    models.Index(fields=["status", "available_at"], name="idx_n8n_outbox_poll"),
                    models.Index(fields=["status", "locked_at"], name="idx_n8n_outbox_stuck"),
                ],
            },
        ),
        migrations.RunPython(protect_inbound_tables, restore_inbound_table_access),
    ]
