# Generated by Django 5.2.13 on 2026-04-20 15:33

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenTrackingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "ticket_id",
                    models.CharField(blank=True, db_index=True, max_length=50, null=True),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "token_tracking_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
