# Generated by Django 5.2.15 on 2026-07-08 02:39

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agents", "0002_tokentrackinglog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationInstance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hubspot_thread_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("hubspot_ticket_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("hubspot_contact_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("channel", models.CharField(blank=True, db_index=True, max_length=50)),
                ("pipeline_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("pipeline_stage_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("NORMALIZED", "Normalized"),
                            ("CONTEXT_HYDRATING", "Context Hydrating"),
                            ("CONTEXT_READY", "Context Ready"),
                            ("CONTACT_REQUIRED", "Contact Required"),
                            ("CONTACT_COLLECTING", "Contact Collecting"),
                            ("CONTACT_ASSOCIATING", "Contact Associating"),
                            ("TRIAGE_PENDING", "Triage Pending"),
                            ("TRIAGE_RUNNING", "Triage Running"),
                            ("AI_SERVICE_PENDING", "AI Service Pending"),
                            ("AI_SERVICE_RUNNING", "AI Service Running"),
                            ("HUMAN_HANDOFF_REQUESTED", "Human Handoff Requested"),
                            ("QUEUE_PENDING", "Queue Pending"),
                            ("HUMAN_ASSIGNED", "Human Assigned"),
                            ("HUMAN_IN_PROGRESS", "Human In Progress"),
                            ("RESOLVED_BY_AI", "Resolved by AI"),
                            ("RESOLVED_BY_HUMAN", "Resolved by Human"),
                            ("CLOSED", "Closed"),
                            ("FAILED_RETRYABLE", "Failed Retryable"),
                            ("FAILED_TERMINAL", "Failed Terminal"),
                            ("IGNORED", "Ignored"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=40,
                    ),
                ),
                ("state_version", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("last_event_id", models.CharField(blank=True, max_length=255)),
                ("last_message_id", models.CharField(blank=True, max_length=255)),
                ("assigned_agent_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ai_session_id", models.CharField(blank=True, max_length=100)),
                ("opened_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("current_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversation_instances",
                "ordering": ["-last_activity_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["state", "last_activity_at"], name="idx_conv_state_activity"),
                    models.Index(fields=["channel", "state"], name="idx_conv_channel_state"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("hubspot_thread_id__isnull", False), models.Q(("hubspot_thread_id", ""), _negated=True)
                        ),
                        fields=("hubspot_thread_id",),
                        name="unique_conversation_instance_thread",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("hubspot_ticket_id__isnull", False), models.Q(("hubspot_ticket_id", ""), _negated=True)
                        ),
                        fields=("hubspot_ticket_id",),
                        name="unique_conversation_instance_ticket",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("agent_name", models.CharField(db_index=True, max_length=100)),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("output_structured", models.JSONField(blank=True, default=dict)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=10)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("STARTED", "Started"), ("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        db_index=True,
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="ai_agents.conversationinstance",
                    ),
                ),
            ],
            options={
                "db_table": "agent_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationStateTransition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("from_state", models.CharField(blank=True, max_length=40)),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("NORMALIZED", "Normalized"),
                            ("CONTEXT_HYDRATING", "Context Hydrating"),
                            ("CONTEXT_READY", "Context Ready"),
                            ("CONTACT_REQUIRED", "Contact Required"),
                            ("CONTACT_COLLECTING", "Contact Collecting"),
                            ("CONTACT_ASSOCIATING", "Contact Associating"),
                            ("TRIAGE_PENDING", "Triage Pending"),
                            ("TRIAGE_RUNNING", "Triage Running"),
                            ("AI_SERVICE_PENDING", "AI Service Pending"),
                            ("AI_SERVICE_RUNNING", "AI Service Running"),
                            ("HUMAN_HANDOFF_REQUESTED", "Human Handoff Requested"),
                            ("QUEUE_PENDING", "Queue Pending"),
                            ("HUMAN_ASSIGNED", "Human Assigned"),
                            ("HUMAN_IN_PROGRESS", "Human In Progress"),
                            ("RESOLVED_BY_AI", "Resolved by AI"),
                            ("RESOLVED_BY_HUMAN", "Resolved by Human"),
                            ("CLOSED", "Closed"),
                            ("FAILED_RETRYABLE", "Failed Retryable"),
                            ("FAILED_TERMINAL", "Failed Terminal"),
                            ("IGNORED", "Ignored"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField()),
                ("actor_type", models.CharField(default="system", max_length=50)),
                ("actor_id", models.CharField(blank=True, max_length=100)),
                ("source_event_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transitions",
                        to="ai_agents.conversationinstance",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_state_transitions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolCallAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("external_object_type", models.CharField(blank=True, max_length=100)),
                ("external_object_id", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_call_audits",
                        to="ai_agents.agentrun",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_call_audits",
                        to="ai_agents.conversationinstance",
                    ),
                ),
            ],
            options={
                "db_table": "tool_call_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("source_event_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("occurred_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("DUPLICATE", "Duplicate"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ai_agents.conversationinstance",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["instance", "event_type"], name="idx_conv_event_type"),
                    models.Index(fields=["source", "source_event_id"], name="idx_conv_event_source"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["instance", "agent_name"], name="idx_agent_run_instance"),
        ),
        migrations.AddIndex(
            model_name="conversationstatetransition",
            index=models.Index(fields=["instance", "created_at"], name="idx_conv_transition_time"),
        ),
        migrations.AddIndex(
            model_name="toolcallauditlog",
            index=models.Index(fields=["instance", "tool_name"], name="idx_tool_audit_instance"),
        ),
    ]
