# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


def normalize_thread_session_ids(apps, schema_editor) -> None:
    """Give every existing thread its canonical, conversation-scoped session."""
    conversation_instance = apps.get_model("ai_agents", "ConversationInstance")
    pending = []
    queryset = conversation_instance.objects.exclude(hubspot_thread_id__isnull=True).exclude(hubspot_thread_id="")
    for instance in queryset.only("id", "hubspot_thread_id", "ai_session_id").iterator(chunk_size=500):
        expected_session_id = f"hubspot-thread-{instance.hubspot_thread_id}"
        if instance.ai_session_id == expected_session_id:
            continue
        instance.ai_session_id = expected_session_id
        pending.append(instance)
        if len(pending) == 500:
            conversation_instance.objects.bulk_update(pending, ["ai_session_id"])
            pending.clear()
    if pending:
        conversation_instance.objects.bulk_update(pending, ["ai_session_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agents", "0005_agent_run_versions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversationinstance",
            name="unique_conversation_instance_ticket",
        ),
        migrations.AlterField(
            model_name="agentsession",
            name="session_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="conversationinstance",
            name="ai_session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tokentrackinglog",
            name="session_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.RunPython(normalize_thread_session_ids, migrations.RunPython.noop),
    ]
