# Generated by Django 5.2.16 on 2026-07-31 17:43

import uuid
import warnings

import django.db.models.deletion
from django.db import migrations, models

PROTECTED_TABLE = "conversation_service_cycles"
CLIENT_ROLES = ("anon", "authenticated")
SUPABASE_DEFAULT_TABLE_PRIVILEGES = "SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER"


def _can_manage_table(schema_editor) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT 1
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                JOIN pg_roles active_role ON active_role.rolname = current_user
                WHERE n.nspname = 'public'
                  AND c.relname = %s
                  AND (
                      active_role.rolsuper
                      OR c.relowner = active_role.oid
                      OR pg_has_role(current_user, c.relowner, 'USAGE')
                  )
            )
            """,
            [PROTECTED_TABLE],
        )
        return bool(cursor.fetchone()[0])


def _client_roles(schema_editor) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        return {str(row[0]) for row in cursor.fetchall()}


def protect_service_cycles(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    if not _can_manage_table(schema_editor):
        warnings.warn(
            f"Operational RLS requires a table-owner connection; skipped: {PROTECTED_TABLE}.",
            RuntimeWarning,
            stacklevel=2,
        )
        return
    quote = schema_editor.connection.ops.quote_name
    qualified_table = f"public.{quote(PROTECTED_TABLE)}"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"COMMENT ON TABLE {qualified_table} IS "
            "'JUDAH operational data; direct anon/authenticated access is prohibited.'"
        )
        for role in _client_roles(schema_editor):
            cursor.execute(f"REVOKE ALL PRIVILEGES ON TABLE {qualified_table} FROM {quote(role)}")
        cursor.execute(f"ALTER TABLE {qualified_table} ENABLE ROW LEVEL SECURITY")


def restore_service_cycle_grants(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql" or not _can_manage_table(schema_editor):
        return
    quote = schema_editor.connection.ops.quote_name
    qualified_table = f"public.{quote(PROTECTED_TABLE)}"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {qualified_table} DISABLE ROW LEVEL SECURITY")
        for role in _client_roles(schema_editor):
            cursor.execute(f"GRANT {SUPABASE_DEFAULT_TABLE_PRIVILEGES} ON TABLE {qualified_table} TO {quote(role)}")


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agents", "0006_remove_unique_conversation_instance_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationServiceCycle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("idempotency_key", models.UUIDField(editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")], db_index=True, default="OPEN", max_length=10
                    ),
                ),
                ("opened_at", models.DateTimeField(db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("opened_from_state", models.CharField(blank=True, max_length=40)),
                ("opened_reason", models.TextField(blank=True)),
                ("opened_by_event_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("closed_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_cycles",
                        to="ai_agents.conversationinstance",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_service_cycles",
                "ordering": ["instance_id", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="service_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_runs",
                to="ai_agents.conversationservicecycle",
            ),
        ),
        migrations.AddField(
            model_name="conversationevent",
            name="service_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="ai_agents.conversationservicecycle",
            ),
        ),
        migrations.AddField(
            model_name="conversationstatetransition",
            name="service_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_transitions",
                to="ai_agents.conversationservicecycle",
            ),
        ),
        migrations.AddField(
            model_name="tokentrackinglog",
            name="service_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_logs",
                to="ai_agents.conversationservicecycle",
            ),
        ),
        migrations.AddField(
            model_name="toolcallauditlog",
            name="service_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_call_audits",
                to="ai_agents.conversationservicecycle",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationservicecycle",
            index=models.Index(fields=["instance", "status"], name="idx_conv_cycle_instance_status"),
        ),
        migrations.AddIndex(
            model_name="conversationservicecycle",
            index=models.Index(fields=["opened_at", "status"], name="idx_conv_cycle_opened_status"),
        ),
        migrations.AddConstraint(
            model_name="conversationservicecycle",
            constraint=models.UniqueConstraint(
                fields=("instance", "sequence"), name="uniq_conv_service_cycle_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationservicecycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")), fields=("instance",), name="uniq_open_conv_service_cycle"
            ),
        ),
        migrations.RunPython(protect_service_cycles, restore_service_cycle_grants),
    ]
