# Generated by Django 5.2.12 on 2026-04-01 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_auto_assignment_tables"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assignedconversation",
            new_name="assigned_co_hubspot_d60a2d_idx",
            old_name="idx_ac_owner_date",
        ),
        migrations.RenameIndex(
            model_name="assignedconversation",
            new_name="assigned_co_assigne_01f772_idx",
            old_name="idx_ac_assigned_at",
        ),
        migrations.RenameIndex(
            model_name="newconversation",
            new_name="new_convers_is_pend_8da81a_idx",
            old_name="idx_nc_pending_queue",
        ),
        migrations.RenameIndex(
            model_name="ticket",
            new_name="tickets_status_1dbab2_idx",
            old_name="tickets_status_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="ticket",
            new_name="tickets_ticket__3d300e_idx",
            old_name="tickets_church_status_idx",
        ),
    ]
