# Generated by Django 5.2.12 on 2026-04-01 06:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "support",
            "0003_rename_idx_ac_owner_date_assigned_co_hubspot_d60a2d_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hubspot_ticket_id", models.TextField(db_index=True, unique=True)),
                (
                    "hubspot_owner_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("agent_name", models.TextField(blank=True, null=True)),
                ("pipeline_id", models.TextField(default="636459134")),
                ("entered_queue_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(db_index=True)),
                ("closed_by_owner_id", models.BigIntegerField(blank=True, null=True)),
                ("closed_by_agent_name", models.TextField(blank=True, null=True)),
                (
                    "queue_wait_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_handle_time_minutes",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("contact_name", models.TextField(blank=True, null=True)),
                ("contact_email", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        db_column="agent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_conversations",
                        to="support.agent",
                    ),
                ),
            ],
            options={
                "db_table": "closed_conversations",
                "ordering": ["-closed_at"],
                "indexes": [
                    models.Index(fields=["closed_at"], name="closed_conv_closed__4939ea_idx"),
                    models.Index(
                        fields=["hubspot_owner_id", "closed_at"],
                        name="closed_conv_hubspot_1f4b60_idx",
                    ),
                ],
            },
        ),
    ]
