# Generated by Django 5.2.12 on 2026-04-01 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_add_closed_conversations"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="newconversation",
            name="new_convers_is_pend_8da81a_idx",
        ),
        migrations.RemoveField(
            model_name="newconversation",
            name="is_pending",
        ),
    ]
