# Generated by Django 5.2.12 on 2026-04-08 11:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0007_newconversation_queue_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationReassignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hubspot_ticket_id", models.TextField(db_index=True)),
                (
                    "from_hubspot_owner_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("from_agent_name", models.TextField(blank=True, null=True)),
                ("to_hubspot_owner_id", models.BigIntegerField(blank=True, null=True)),
                ("to_agent_name", models.TextField(blank=True, null=True)),
                ("reassigned_at", models.DateTimeField(db_index=True)),
                (
                    "time_with_previous_agent_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("reassignment_source", models.TextField(default="hubspot_webhook")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_agent",
                    models.ForeignKey(
                        blank=True,
                        db_column="from_agent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_from",
                        to="support.agent",
                    ),
                ),
                (
                    "to_agent",
                    models.ForeignKey(
                        blank=True,
                        db_column="to_agent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_to",
                        to="support.agent",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_reassignments",
                "ordering": ["-reassigned_at"],
                "indexes": [
                    models.Index(
                        fields=["hubspot_ticket_id", "reassigned_at"],
                        name="conversatio_hubspot_5e2d36_idx",
                    ),
                    models.Index(
                        fields=["from_hubspot_owner_id", "reassigned_at"],
                        name="conversatio_from_hu_57950b_idx",
                    ),
                    models.Index(
                        fields=["to_hubspot_owner_id", "reassigned_at"],
                        name="conversatio_to_hubs_481891_idx",
                    ),
                ],
            },
        ),
    ]
