# Generated by Django 5.2.12 on 2026-04-13 16:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0008_add_conversation_reassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="away_time_seconds_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_status_change_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="online_time_seconds_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="sat_last_count_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="sat_last_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_assignments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignedconversation",
            name="assignment_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="closedconversation",
            name="closure_source",
            field=models.CharField(default="agent", max_length=20),
        ),
        migrations.AddField(
            model_name="closedconversation",
            name="resolution_time_minutes",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name="AgentDailyTimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("log_date", models.DateField(db_index=True)),
                ("online_time_seconds", models.IntegerField(default=0)),
                ("away_time_seconds", models.IntegerField(default=0)),
                ("status_transitions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        db_column="agent_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_time_logs",
                        to="support.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_daily_time_logs",
                "ordering": ["-log_date"],
                "constraints": [models.UniqueConstraint(fields=("agent", "log_date"), name="unique_agent_daily_log")],
            },
        ),
    ]
