# Generated by Django 5.2.12 on 2026-04-15 01:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0009_sat_matchmaker_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHoursConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="default", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("monday_start", models.IntegerField(default=9)),
                ("monday_end", models.IntegerField(default=18)),
                ("tuesday_start", models.IntegerField(default=9)),
                ("tuesday_end", models.IntegerField(default=18)),
                ("wednesday_start", models.IntegerField(default=9)),
                ("wednesday_end", models.IntegerField(default=18)),
                ("thursday_start", models.IntegerField(default=9)),
                ("thursday_end", models.IntegerField(default=18)),
                ("friday_start", models.IntegerField(default=9)),
                ("friday_end", models.IntegerField(default=18)),
                ("saturday_start", models.IntegerField(default=9)),
                ("saturday_end", models.IntegerField(default=13)),
                ("sunday_start", models.IntegerField(default=8)),
                ("sunday_end", models.IntegerField(default=12)),
                (
                    "timezone_name",
                    models.CharField(default="America/Sao_Paulo", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_hours_config",
            },
        ),
        migrations.CreateModel(
            name="SpecialSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("closed", "Closed (no operation)"),
                            ("custom", "Custom hours"),
                        ],
                        default="closed",
                        max_length=20,
                    ),
                ),
                ("start_hour", models.IntegerField(blank=True, null=True)),
                ("end_hour", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "special_schedules",
                "ordering": ["-date"],
            },
        ),
    ]
