# Generated by Django 5.2.15 on 2026-07-13 20:29

from django.db import migrations, models

import apps.support.models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0012_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedconversation",
            name="pipeline_id",
            field=models.TextField(default=apps.support.models.default_support_pipeline_id),
        ),
        migrations.AlterField(
            model_name="closedconversation",
            name="pipeline_id",
            field=models.TextField(default=apps.support.models.default_support_pipeline_id),
        ),
        migrations.AlterField(
            model_name="newconversation",
            name="pipeline_id",
            field=models.TextField(default=apps.support.models.default_support_pipeline_id),
        ),
    ]
