# Generated by Django 5.2 for absence-safe availability reconciliation.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0014_newconversation_failure_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="availability_fencing_token",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="availability_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="availability_online_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="availability_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="availability_sample_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="availability_writer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="eligibility_evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="eligibility_reason",
            field=models.CharField(default="never_observed", max_length=64),
        ),
        migrations.AddField(
            model_name="agent",
            name="eligibility_state",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("ineligible", "Ineligible"),
                    ("eligible", "Eligible"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="hubspot_user_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="remote_availability_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="agent",
            name="remote_out_of_office_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="remote_timezone",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agent",
            name="remote_working_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AvailabilityReconciliationLease",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                ("writer_id", models.CharField(blank=True, default="", max_length=255)),
                ("runtime_environment", models.CharField(blank=True, default="", max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "availability_reconciliation_leases",
            },
        ),
        migrations.CreateModel(
            name="AgentAvailabilityDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision", models.PositiveBigIntegerField()),
                ("old_status", models.CharField(blank=True, default="", max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("remote_status", models.CharField(blank=True, default="", max_length=32)),
                ("raw_state_hash", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                ("eligibility_state", models.CharField(max_length=16)),
                ("eligibility_reason", models.CharField(max_length=64)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                ("writer_id", models.CharField(max_length=255)),
                ("runtime_environment", models.CharField(max_length=64)),
                ("fencing_token", models.PositiveBigIntegerField()),
                ("metadata_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        db_column="agent_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_decisions",
                        to="support.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_availability_decisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["eligibility_state", "availability_observed_at"],
                name="idx_agent_safe_eligibility",
            ),
        ),
        migrations.AddIndex(
            model_name="agentavailabilitydecision",
            index=models.Index(fields=["agent", "-created_at"], name="idx_avail_decision_agent"),
        ),
        migrations.AddIndex(
            model_name="agentavailabilitydecision",
            index=models.Index(fields=["writer_id", "-created_at"], name="idx_avail_decision_writer"),
        ),
        migrations.AddConstraint(
            model_name="agentavailabilitydecision",
            constraint=models.UniqueConstraint(
                fields=("agent", "revision"),
                name="uniq_agent_availability_revision",
            ),
        ),
    ]
