# Generated by Django 5.2 for the production new-ticket rollout boundary.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0017_durable_assignment_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="newconversation",
            name="automatic_assignment_eligible",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=("True only for tickets ingested by the live webhook path after the rollout gate."),
            ),
        ),
    ]
