# Generated by Django 5.2.16 on 2026-07-31 17:43

import uuid
import warnings

import django.db.models.deletion
from django.db import migrations, models

PROTECTED_TABLE = "conversation_instance_attendants"
CLIENT_ROLES = ("anon", "authenticated")
SUPABASE_DEFAULT_TABLE_PRIVILEGES = "SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER"


def _can_manage_table(schema_editor) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT 1
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                JOIN pg_roles active_role ON active_role.rolname = current_user
                WHERE n.nspname = 'public'
                  AND c.relname = %s
                  AND (
                      active_role.rolsuper
                      OR c.relowner = active_role.oid
                      OR pg_has_role(current_user, c.relowner, 'USAGE')
                  )
            )
            """,
            [PROTECTED_TABLE],
        )
        return bool(cursor.fetchone()[0])


def _client_roles(schema_editor) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        return {str(row[0]) for row in cursor.fetchall()}


def protect_attendant_history(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    if not _can_manage_table(schema_editor):
        warnings.warn(
            f"Operational RLS requires a table-owner connection; skipped: {PROTECTED_TABLE}.",
            RuntimeWarning,
            stacklevel=2,
        )
        return
    quote = schema_editor.connection.ops.quote_name
    qualified_table = f"public.{quote(PROTECTED_TABLE)}"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"COMMENT ON TABLE {qualified_table} IS "
            "'JUDAH operational data; direct anon/authenticated access is prohibited.'"
        )
        for role in _client_roles(schema_editor):
            cursor.execute(f"REVOKE ALL PRIVILEGES ON TABLE {qualified_table} FROM {quote(role)}")
        cursor.execute(f"ALTER TABLE {qualified_table} ENABLE ROW LEVEL SECURITY")


def restore_attendant_grants(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql" or not _can_manage_table(schema_editor):
        return
    quote = schema_editor.connection.ops.quote_name
    qualified_table = f"public.{quote(PROTECTED_TABLE)}"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {qualified_table} DISABLE ROW LEVEL SECURITY")
        for role in _client_roles(schema_editor):
            cursor.execute(f"GRANT {SUPABASE_DEFAULT_TABLE_PRIVILEGES} ON TABLE {qualified_table} TO {quote(role)}")


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agents", "0007_conversationservicecycle_agentrun_service_cycle_and_more"),
        ("support", "0026_protect_operational_tables_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationInstanceAttendant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hubspot_owner_id", models.BigIntegerField(db_index=True)),
                ("agent_name", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("automatic_assignment", "Automatic assignment"),
                            ("manual_assignment", "Manual assignment"),
                            ("owner_change", "Owner change"),
                            ("forced_reassignment", "Forced reassignment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation_instance_attendances",
                        to="support.agent",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendants",
                        to="ai_agents.conversationinstance",
                    ),
                ),
                (
                    "service_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendants",
                        to="ai_agents.conversationservicecycle",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_instance_attendants",
                "ordering": ["instance_id", "service_cycle_id", "first_seen_at"],
                "indexes": [
                    models.Index(fields=["instance", "first_seen_at"], name="idx_conv_attendant_instance"),
                    models.Index(fields=["agent", "first_seen_at"], name="idx_conv_attendant_agent"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("service_cycle", "agent"), name="uniq_conv_cycle_attendant")
                ],
            },
        ),
        migrations.RunPython(protect_attendant_history, restore_attendant_grants),
    ]
