# Generated by Django 5.2.15 on 2026-08-12 03:49

import uuid
from datetime import date, time

import django.db.models.deletion
from django.db import migrations, models

WEEKDAYS = (
    (0, "monday", "Segunda-feira", 9, 18),
    (1, "tuesday", "Terça-feira", 9, 18),
    (2, "wednesday", "Quarta-feira", 9, 18),
    (3, "thursday", "Quinta-feira", 9, 18),
    (4, "friday", "Sexta-feira", 9, 18),
    (5, "saturday", "Sábado", 9, 13),
    (6, "sunday", "Domingo", 8, 12),
)

HOLIDAYS_2026 = {
    date(2026, 1, 1): "Confraternização Universal",
    date(2026, 2, 16): "Carnaval (segunda)",
    date(2026, 2, 17): "Carnaval (terça)",
    date(2026, 4, 3): "Sexta-feira Santa",
    date(2026, 4, 21): "Tiradentes",
    date(2026, 5, 1): "Dia do Trabalho",
    date(2026, 6, 4): "Corpus Christi",
    date(2026, 9, 7): "Independência do Brasil",
    date(2026, 10, 12): "Nossa Senhora Aparecida",
    date(2026, 11, 2): "Finados",
    date(2026, 11, 15): "Proclamação da República",
    date(2026, 12, 24): "Véspera de Natal (InChurch)",
    date(2026, 12, 25): "Natal",
    date(2026, 12, 31): "Véspera de Ano Novo (InChurch)",
}


def migrate_legacy_calendar(apps, schema_editor):
    """Materialize legacy business hours and exceptions as editable rules."""
    BusinessHoursConfig = apps.get_model("support", "BusinessHoursConfig")
    SpecialSchedule = apps.get_model("support", "SpecialSchedule")
    schedule_model = apps.get_model("support", "HelpdeskSchedule")
    rule_model = apps.get_model("support", "HelpdeskScheduleRule")
    interval_model = apps.get_model("support", "HelpdeskScheduleInterval")

    schedule, _ = schedule_model.objects.get_or_create(
        status="published",
        defaults={"timezone_name": "America/Sao_Paulo", "version": 1},
    )
    config = BusinessHoursConfig.objects.filter(is_active=True).order_by("pk").first()

    def add_rule(*, name, rule_type, recurrence, starts_on, weekdays=None, dates=None, priority=0, intervals=None):
        rule, created = rule_model.objects.get_or_create(
            schedule=schedule,
            name=name,
            defaults={
                "rule_type": rule_type,
                "recurrence": recurrence,
                "starts_on": starts_on,
                "weekdays": weekdays or [],
                "dates": [item.isoformat() for item in (dates or [])],
                "priority": priority,
                "is_active": True,
                "version": 1,
            },
        )
        if created:
            interval_model.objects.bulk_create(
                [interval_model(rule=rule, start=start, end=end) for start, end in (intervals or [])]
            )
        return rule

    for weekday, field, label, default_start, default_end in WEEKDAYS:
        start_hour = getattr(config, f"{field}_start", default_start) if config else default_start
        end_hour = getattr(config, f"{field}_end", default_end) if config else default_end
        start_at = time(start_hour)
        end_at = time(17, 50) if weekday <= 4 and start_hour == 9 and end_hour == 18 else time(end_hour)
        intervals = [(start_at, end_at)]
        if weekday == 3 and start_at < time(12) and end_at > time(13):
            intervals = [(start_at, time(12)), (time(13), end_at)]
        add_rule(
            name=f"Atendimento legado — {label}",
            rule_type="service",
            recurrence="weekly",
            starts_on=date(1970, 1, 1),
            weekdays=[weekday],
            intervals=intervals,
        )

    special_dates = set(SpecialSchedule.objects.values_list("date", flat=True))
    for holiday, label in HOLIDAYS_2026.items():
        if holiday in special_dates:
            continue
        add_rule(
            name=f"Feriado legado — {label}",
            rule_type="absence",
            recurrence="once",
            starts_on=holiday,
            dates=[holiday],
            priority=100,
        )

    for special in SpecialSchedule.objects.order_by("date", "pk"):
        if special.schedule_type == "closed":
            add_rule(
                name=f"Exceção legada — {special.reason or special.date.isoformat()}",
                rule_type="absence",
                recurrence="once",
                starts_on=special.date,
                dates=[special.date],
                priority=200,
            )
        elif special.start_hour is not None and special.end_hour is not None:
            add_rule(
                name=f"Horário especial legado — {special.reason or special.date.isoformat()}",
                rule_type="service",
                recurrence="once",
                starts_on=special.date,
                dates=[special.date],
                priority=200,
                intervals=[(time(special.start_hour), time(special.end_hour))],
            )

    schedule.version = rule_model.objects.filter(schedule=schedule).count() + 1
    schedule.save(update_fields=["version", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0027_conversationinstanceattendant"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpdeskSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timezone_name", models.CharField(default="America/Sao_Paulo", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")], default="published", max_length=16
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "helpdesk_schedules",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "published")),
                        fields=("status",),
                        name="helpdesk_schedule_one_published",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpdeskScheduleRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                (
                    "rule_type",
                    models.CharField(choices=[("service", "Service"), ("absence", "Absence")], max_length=16),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[("once", "Once"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=16,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("weekdays", models.JSONField(blank=True, default=list)),
                ("week_of_month", models.SmallIntegerField(blank=True, null=True)),
                ("dates", models.JSONField(blank=True, default=list)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="support.helpdeskschedule"
                    ),
                ),
            ],
            options={
                "db_table": "helpdesk_schedule_rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpdeskScheduleInterval",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("weekday", models.SmallIntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervals",
                        to="support.helpdeskschedulerule",
                    ),
                ),
            ],
            options={
                "db_table": "helpdesk_schedule_intervals",
            },
        ),
        migrations.CreateModel(
            name="HelpdeskAbsenceMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rich_text", models.TextField(blank=True, default="")),
                ("plain_text", models.TextField(blank=True, default="")),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_message",
                        to="support.helpdeskschedulerule",
                    ),
                ),
            ],
            options={
                "db_table": "helpdesk_absence_messages",
            },
        ),
        migrations.AddIndex(
            model_name="helpdeskschedulerule",
            index=models.Index(fields=["schedule", "is_active", "starts_on"], name="helpdesk_rule_active_idx"),
        ),
        migrations.AddIndex(
            model_name="helpdeskschedulerule",
            index=models.Index(fields=["rule_type", "recurrence", "priority"], name="helpdesk_rule_match_idx"),
        ),
        migrations.AddConstraint(
            model_name="helpdeskschedulerule",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__isnull", True), ("ends_on__gte", models.F("starts_on")), _connector="OR"),
                name="helpdesk_rule_valid_date_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="helpdeskschedulerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("week_of_month__isnull", True),
                    models.Q(("week_of_month__gte", 1), ("week_of_month__lte", 5)),
                    _connector="OR",
                ),
                name="helpdesk_rule_valid_week",
            ),
        ),
        migrations.AddConstraint(
            model_name="helpdeskschedulerule",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 0)), name="helpdesk_rule_priority_nonnegative"
            ),
        ),
        migrations.AddIndex(
            model_name="helpdeskscheduleinterval",
            index=models.Index(fields=["rule", "date", "weekday"], name="helpdesk_interval_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="helpdeskscheduleinterval",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gt", models.F("start"))), name="helpdesk_interval_increasing"
            ),
        ),
        migrations.AddConstraint(
            model_name="helpdeskscheduleinterval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weekday__isnull", True), models.Q(("weekday__gte", 0), ("weekday__lte", 6)), _connector="OR"
                ),
                name="helpdesk_interval_valid_weekday",
            ),
        ),
        migrations.RunPython(migrate_legacy_calendar, migrations.RunPython.noop),
    ]
