# Generated by Django 5.2.15 on 2026-09-08 02:46

import uuid

import django.db.models.deletion
from django.db import migrations, models

TABLES = ("support_ticket_occupancies", "agent_capacity_reservations")


def protect_capacity_tables(apps, schema_editor):
    """Extend existing routing writer guards and deny public API access."""
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles")
        roles = {row[0] for row in cursor.fetchall()}
        for table in TABLES:
            cursor.execute(f"REVOKE ALL ON TABLE {table} FROM PUBLIC")
            for role in ("anon", "authenticated"):
                if role in roles:
                    cursor.execute(f"REVOKE ALL ON TABLE {table} FROM {role}")
            cursor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            for role in ("judah_production_runtime", "judah_staging_runtime"):
                if role in roles:
                    cursor.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {table} TO {role}")
            cursor.execute(
                f"CREATE TRIGGER trg_guard_{table}_runtime BEFORE INSERT OR UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION judah_reject_non_authoritative_runtime()"
            )
        cursor.execute(
            "COMMENT ON INDEX idx_occupancy_agent_state IS 'Find active identified occupancy and portfolio reconciliation candidates.'"
        )
        cursor.execute(
            "COMMENT ON INDEX idx_capacity_agent_state IS 'Find held reservations for the per-agent occupancy union.'"
        )
        cursor.execute(
            "CREATE TRIGGER trg_guard_agent_capacity_metadata BEFORE UPDATE OF capacity_revision, "
            "capacity_state, capacity_reconciled_at ON agents FOR EACH ROW "
            "EXECUTE FUNCTION judah_reject_non_authoritative_runtime()"
        )


def unprotect_capacity_tables(apps, schema_editor):
    """Remove only capacity guards before reversing the additive schema."""
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in TABLES:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS trg_guard_{table}_runtime ON {table}")
    schema_editor.execute("DROP TRIGGER IF EXISTS trg_guard_agent_capacity_metadata ON agents")


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0030_opening_assignment_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="capacity_reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="capacity_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="capacity_state",
            field=models.CharField(default="uninitialized", max_length=16),
        ),
        migrations.CreateModel(
            name="SupportTicketOccupancy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_account_id", models.CharField(max_length=64)),
                ("hubspot_ticket_id", models.TextField()),
                ("hubspot_owner_id", models.BigIntegerField(blank=True, null=True)),
                ("pipeline_id", models.TextField(default="")),
                ("state", models.CharField(default="unknown", max_length=16)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("provider_updated_at", models.DateTimeField(blank=True, null=True)),
                ("observation_source", models.CharField(default="", max_length=64)),
                ("observation_id", models.CharField(default="", max_length=128)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="support.agent"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="support.supportconversationcycle",
                    ),
                ),
            ],
            options={
                "db_table": "support_ticket_occupancies",
            },
        ),
        migrations.CreateModel(
            name="AgentCapacityReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation_key", models.CharField(max_length=128, unique=True)),
                ("state", models.CharField(default="held", max_length=16)),
                ("held_at", models.DateTimeField()),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
                ("conclusion_reason", models.CharField(default="", max_length=128)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="support.agent")),
                (
                    "assignment_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support.assignmentattempt",
                    ),
                ),
                (
                    "reassignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support.conversationreassignment",
                    ),
                ),
                (
                    "occupancy",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="support.supportticketoccupancy"),
                ),
            ],
            options={
                "db_table": "agent_capacity_reservations",
            },
        ),
        migrations.AddIndex(
            model_name="supportticketoccupancy",
            index=models.Index(fields=["agent", "state"], name="idx_occupancy_agent_state"),
        ),
        migrations.AddConstraint(
            model_name="supportticketoccupancy",
            constraint=models.UniqueConstraint(
                fields=("source_account_id", "hubspot_ticket_id"), name="uq_occupancy_ticket"
            ),
        ),
        migrations.AddConstraint(
            model_name="supportticketoccupancy",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["unknown", "active", "unassigned", "closed", "out_of_scope"])),
                name="ck_occupancy_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportticketoccupancy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "active"), _negated=True), ("hubspot_owner_id__isnull", False), _connector="OR"
                ),
                name="ck_active_occupancy_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="agentcapacityreservation",
            index=models.Index(fields=["agent", "state"], name="idx_capacity_agent_state"),
        ),
        migrations.AddConstraint(
            model_name="agentcapacityreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assignment_attempt__isnull", False), ("reassignment__isnull", True)),
                    models.Q(("assignment_attempt__isnull", True), ("reassignment__isnull", False)),
                    _connector="OR",
                ),
                name="ck_capacity_operation_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcapacityreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("concluded_at__isnull", True), ("state", "held")),
                    models.Q(("concluded_at__isnull", False), ("state__in", ["converted", "released"])),
                    _connector="OR",
                ),
                name="ck_capacity_conclusion",
            ),
        ),
        migrations.RunPython(protect_capacity_tables, unprotect_capacity_tables),
    ]
