# Generated by Django 5.2.17 on 2026-09-28 15:02

import uuid

from django.db import migrations, models

OCCURRENCE_TABLE = "support_lifecycle_occurrences"


def protect_occurrence_table(_apps, schema_editor):
    """Keep provider evidence behind the same runtime guard as capacity rows."""
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles")
        roles = {row[0] for row in cursor.fetchall()}
        cursor.execute(f"REVOKE ALL ON TABLE {OCCURRENCE_TABLE} FROM PUBLIC")
        for role in ("anon", "authenticated"):
            if role in roles:
                cursor.execute(f"REVOKE ALL ON TABLE {OCCURRENCE_TABLE} FROM {role}")
        cursor.execute(f"ALTER TABLE {OCCURRENCE_TABLE} ENABLE ROW LEVEL SECURITY")
        for role in ("judah_production_runtime", "judah_staging_runtime"):
            if role in roles:
                cursor.execute(f"GRANT SELECT, INSERT, UPDATE ON TABLE {OCCURRENCE_TABLE} TO {role}")
        cursor.execute(
            f"CREATE TRIGGER trg_guard_{OCCURRENCE_TABLE}_runtime BEFORE INSERT OR UPDATE OR DELETE "
            f"ON {OCCURRENCE_TABLE} FOR EACH ROW EXECUTE FUNCTION judah_reject_non_authoritative_runtime()"
        )


def unprotect_occurrence_table(_apps, schema_editor):
    """Remove the runtime trigger before Django reverses the table creation."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"DROP TRIGGER IF EXISTS trg_guard_{OCCURRENCE_TABLE}_runtime ON {OCCURRENCE_TABLE}")


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0032_grant_conversation_attendant_runtime_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportLifecycleOccurrence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="hubspot", max_length=32)),
                ("source_account_id", models.CharField(max_length=64)),
                ("hubspot_ticket_id", models.TextField()),
                (
                    "occurrence_type",
                    models.CharField(
                        choices=[
                            ("entered_support_queue", "Entered Support Queue"),
                            ("closed", "Closed"),
                            ("owner_changed", "Owner Changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evidence_status",
                    models.CharField(
                        choices=[
                            ("proven", "Proven"),
                            ("provider_materialization_pending", "Provider Materialization Pending"),
                            ("ambiguous", "Ambiguous"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=40,
                    ),
                ),
                ("evidence_source", models.CharField(max_length=64)),
                ("evidence_key", models.TextField(unique=True)),
                ("source_event_id", models.TextField(blank=True, default="")),
                ("provider_updated_at", models.DateTimeField(blank=True, null=True)),
                ("observation_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("repair_required", "Repair Required"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("next_reconcile_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "support_lifecycle_occurrences",
                "indexes": [
                    models.Index(
                        fields=["hubspot_ticket_id", "occurrence_type", "occurred_at"], name="idx_occ_ticket_type_time"
                    ),
                    models.Index(fields=["processing_status", "next_reconcile_at"], name="idx_occ_status_reconcile"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("evidence_status", "proven"), _negated=True),
                            ("occurred_at__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_occ_proven_has_time",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("evidence_status", "provider_materialization_pending"), _negated=True),
                            models.Q(("processing_status", "processed"), _negated=True),
                            _connector="OR",
                        ),
                        name="ck_occ_pending_unprocessed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("retry_count__gte", 0)), name="ck_occ_retry_nonnegative"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("occurred_at__isnull", False)),
                        fields=(
                            "source_system",
                            "source_account_id",
                            "hubspot_ticket_id",
                            "occurrence_type",
                            "occurred_at",
                        ),
                        name="uq_occ_temporal_identity",
                    ),
                ],
            },
        ),
        migrations.RunPython(protect_occurrence_table, unprotect_occurrence_table),
    ]
