# Generated by Django 5.2.17 on 2026-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0033_supportlifecycleoccurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationinstanceattendant",
            name="source",
            field=models.CharField(
                choices=[
                    ("automatic_assignment", "Automatic assignment"),
                    ("manual_assignment", "Manual assignment"),
                    ("owner_change", "Owner change"),
                    ("forced_reassignment", "Forced reassignment"),
                    ("external_integration", "External integration"),
                    ("unknown_external", "Unknown external origin"),
                ],
                max_length=32,
            ),
        ),
    ]
