"use client";

import { useEffect, useRef, useState } from "react";

interface SandboxUser {
  email: string;
  firstName: string;
  id: number;
  lastName: string;
}

interface SandboxChatProps {
  portalId: string;
  user: SandboxUser;
}

interface VisitorTokenPayload {
  token: string;
}

interface HubSpotWidget {
  load: (options?: { widgetOpen?: boolean }) => void;
  remove: () => void;
  status: () => { loaded: boolean };
}

type HubSpotEventHandler = () => void;

declare global {
  interface Window {
    HubSpotConversations?: {
      off: (eventName: "widgetLoaded", handler: HubSpotEventHandler) => void;
      on: (eventName: "widgetLoaded", handler: HubSpotEventHandler) => void;
      widget: HubSpotWidget;
    };
    _hsq?: unknown[];
    hsConversationsOnReady?: Array<() => void>;
    hsConversationsSettings?: {
      identificationEmail?: string;
      identificationToken?: string;
      inlineEmbedSelector?: string;
      loadImmediately?: boolean;
    };
  }
}

// This is the HubSpot tracking-code loader ID. Keeping the official ID avoids
// loading a second tracker if the host page already includes the embed code.
const scriptId = "hs-script-loader";

/** Renders HubSpot's official web chat widget only on the sandbox test route. */
export function SandboxChat({ portalId, user }: SandboxChatProps) {
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState("Autenticando visitante no HubSpot…");
  const widgetWasLoadedRef = useRef(false);

  useEffect(() => {
    let cancelled = false;
    let widgetLoadTimeout: ReturnType<typeof setTimeout> | undefined;
    let widgetLoadedHandler: HubSpotEventHandler | undefined;

    const markWidgetLoaded = () => {
      if (!cancelled) {
        widgetWasLoadedRef.current = true;
        setError(null);
        setStatus("Chat conectado à sandbox");
      }
    };

    const configureWidget = (token: VisitorTokenPayload) => {
      if (cancelled) {
        return;
      }

      window._hsq = window._hsq ?? [];
      window._hsq.push([
        "identify",
        {
          email: user.email,
          firstname: user.firstName,
          lastname: user.lastName,
        },
      ]);
      window._hsq.push(["trackPageView"]);

      window.hsConversationsSettings = {
        loadImmediately: false,
        inlineEmbedSelector: "#hubspot-sandbox-chat",
        identificationEmail: user.email,
        identificationToken: token.token,
      };

      const loadWidget = () => {
        const conversations = window.HubSpotConversations;
        if (!conversations || cancelled) {
          return;
        }

        widgetLoadedHandler = markWidgetLoaded;
        conversations.on("widgetLoaded", widgetLoadedHandler);
        conversations.widget.load({ widgetOpen: true });

        if (conversations.widget.status().loaded) {
          markWidgetLoaded();
          return;
        }

        widgetLoadTimeout = setTimeout(() => {
          if (!cancelled && !window.HubSpotConversations?.widget.status().loaded) {
            setError(
              "O HubSpot não disponibilizou um chatflow para esta URL. Confirme se o chatflow da sandbox está publicado e inclui judah-admin.staging.febrate.com/sandbox-chat.",
            );
            setStatus("Chat indisponível");
          }
        }, 10_000);
      };

      if (window.HubSpotConversations) {
        loadWidget();
        return;
      }

      window.hsConversationsOnReady = [...(window.hsConversationsOnReady ?? []), loadWidget];
      const existingScript = document.getElementById(scriptId);
      if (existingScript) {
        return;
      }

      const script = document.createElement("script");
      script.id = scriptId;
      script.async = true;
      script.defer = true;
      // The sandbox portal lives in HubSpot's NA1 data center. This matches
      // the tracking code generated by HubSpot for portal 51734496.
      script.src = `https://js-na1.hs-scripts.com/${portalId}.js`;
      script.onerror = () => {
        if (!cancelled) {
          setError("Não foi possível carregar o widget do HubSpot.");
        }
      };
      document.head.appendChild(script);
    };

    const initialise = async () => {
      try {
        const response = await fetch("/api/hubspot/visitor-token", { method: "POST" });
        const payload = (await response.json()) as VisitorTokenPayload | { detail?: string };

        if (!response.ok || !("token" in payload)) {
          throw new Error("detail" in payload ? payload.detail : "Falha ao autenticar o chat.");
        }

        configureWidget(payload);
      } catch (cause) {
        if (!cancelled) {
          setError(cause instanceof Error ? cause.message : "Falha ao iniciar o chat.");
          setStatus("Chat indisponível");
        }
      }
    };

    void initialise();

    return () => {
      cancelled = true;
      if (widgetLoadTimeout) {
        clearTimeout(widgetLoadTimeout);
      }
      if (widgetLoadedHandler) {
        window.HubSpotConversations?.off("widgetLoaded", widgetLoadedHandler);
      }
      if (widgetWasLoadedRef.current) {
        window.HubSpotConversations?.widget.remove();
        widgetWasLoadedRef.current = false;
      }
    };
  }, [portalId, user.email, user.firstName, user.lastName]);

  return (
    <main className="relative z-10 flex min-h-svh items-center justify-center px-4 py-10">
      <section className="w-full max-w-2xl rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--surface-shadow)] sm:p-9">
        <p className="judah-mono text-[10px] uppercase tracking-[0.28em] text-[var(--muted)]">
          HubSpot sandbox · portal {portalId}
        </p>
        <h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Chat de teste</h1>
        <p className="mt-2 text-sm text-[var(--muted)]">
          Sessão Judah autenticada como {user.email}. As mensagens desta página são enviadas somente ao chatflow
          configurado na sandbox HubSpot.
        </p>
        <p className="mt-5 text-xs font-medium text-[var(--accent-foreground)]" role="status">
          {status}
        </p>
        {error ? (
          <p className="mt-3 rounded-[var(--radius-sm)] bg-red-500/10 px-3 py-2 text-sm text-[var(--danger)]" role="alert">
            {error}
          </p>
        ) : null}
        <div id="hubspot-sandbox-chat" className="mt-6 min-h-[520px] overflow-hidden rounded-[var(--radius-md)]" />
        <style jsx global>{`
          #hubspot-sandbox-chat,
          #hubspot-sandbox-chat #hubspot-conversations-inline-parent,
          #hubspot-sandbox-chat #hubspot-conversations-inline-iframe {
            width: 100%;
            min-height: 520px;
          }

          #hubspot-sandbox-chat #hubspot-conversations-inline-iframe {
            border: 0;
            height: min(560px, 70svh);
          }
        `}</style>
      </section>
    </main>
  );
}
